all: main.cpp linkedlist.h linkedlist.cpp hashtable.h hashtable.cpp maxheap.h maxheap.cpp heaptable.h heaptable.cpp
	g++ -std=c++11 -Wall main.cpp linkedlist.cpp hashtable.cpp maxheap.cpp heaptable.cpp -o prog1

clean:
	rm -f main
